import { MRFDocument } from '../types/mrf';

/**
 * EXACT Official Filled MRF Benchmark Document
 * Directly cloned from the user's provided file:
 * NOKIA-FN_06302026-004_MIN1371-GNG-701_MF2_JOHN_CARLO_RABANES.xlsx
 * 
 * Exact Cell Placement Rules:
 * - B6: Originating Warehouse ("Paranaque WHS")
 * - E6:G6 (merged): Date (formula =TODAY(), formatted date)
 * - B8: BLANK
 * - E8:G8 (merged): DESTINATON ("CAGAYAN DE ORO")
 * - B10: BLANK
 * - E10:G10 (merged): SITE ID ("MIN1371  - GNG_701")
 * - E11:G12 (merged): SITE ADDRESS ("HUAWEI CABINET CORNER CUERDORIZAL ST., FRONT OF DMS RTW , GINGOOG CITY")
 * - Rows 18-25: Main Equipment (Col A: Part Number, Col B: Description, Col C: BLANK, Col D: REQ QTY, Col E, F, G: BLANK)
 * - Row 26: Section Divider "LOCAL MATERIALS/ ACCESSORIES"
 * - Rows 27-46: Local Materials (Col A: Part Number, Col B: Description, Col C: BLANK, Col D: REQ QTY, Col E: UoM e.g. "pcs", "pc", "m", Col F, G: BLANK)
 * - Rows 47-51: Signatures and Contacts:
 *   - A48:A49: "Request by: JOHN CARLO RABANES"
 *   - D47:G47: "NOKIA INHOUSE - JOHN CARLO RABANES/09669343065"
 *   - D48:G48: "DNA SUBCON - EASTMOND MIRANDA/09543991868"
 * - Rows 56-57: MRF Reference Stamp
 */
export const OFFICIAL_FILLED_MRF_BENCHMARK: MRFDocument = {
  id: 'mrf_benchmark_min1371_gng_701',
  createdAt: '2026-06-30T00:00:00.000Z',
  updatedAt: '2026-06-30T00:00:00.000Z',
  header: {
    mrfNumber: 'NOKIA-FN_06302026-004_MIN1371-GNG-701_MF2_JOHN_CARLO_RABANES',
    fromWarehouse: 'Paranaque WHS',
    date: '2026-06-30',
    destinationCode: '',
    destination: 'CAGAYAN DE ORO',
    siteId: 'MIN1371  - GNG_701',
    siteAddress: 'HUAWEI CABINET CORNER CUERDORIZAL ST., FRONT OF DMS RTW , GINGOOG CITY',
    project: 'Globe Telecom / Nokia FN OLT Rollout',
  },
  mainItems: [
    {
      id: 'mi_bench_1',
      partNumber: '3FE76762AA',
      description: 'Lightspan MF-2 shelf incl. fan unit (LMXR-A)',
      packageNo: '',
      uom: 'PC',
      qtyReq: 1,
      qtyIssued: 'PC',
      qtyReceived: '',
      qtyBalance: '',
      category: 'MF2',
    },
    {
      id: 'mi_bench_2',
      partNumber: '3FE76518AA',
      description: 'MF2-FAN Module',
      packageNo: '',
      uom: 'PC',
      qtyReq: 1,
      qtyIssued: 'PC',
      qtyReceived: '',
      qtyBalance: '',
      category: 'MF2',
    },
    {
      id: 'mi_bench_3',
      partNumber: '3FE76559BA',
      description: 'Lightspan MF-2 DC power module (LPWR-B DC)',
      packageNo: '',
      uom: 'PC',
      qtyReq: 2,
      qtyIssued: 'PC',
      qtyReceived: '',
      qtyBalance: '',
      category: 'MF2',
    },
    {
      id: 'mi_bench_4',
      partNumber: '3FE62600AA',
      description: 'Optical Transceiver SFP+,1310nm SM,10km(brand: Nokia) (10GBase-LR)',
      packageNo: '',
      uom: 'PC',
      qtyReq: 2,
      qtyIssued: 'PC',
      qtyReceived: '',
      qtyBalance: '',
      category: 'MF2',
    },
    {
      id: 'mi_bench_5',
      partNumber: '3FE53441AA',
      description: 'PON Transceiver20km 1310nm(Tx)1490nm(Rx) - GPON SFP B+',
      packageNo: '',
      uom: 'PC',
      qtyReq: 8,
      qtyIssued: 'PC',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Patch Cord',
    },
    {
      id: 'mi_bench_6',
      partNumber: '3FE47581AB',
      description: 'Transcvr XGS-PON/GPON MPM B+(28dBm)Ctemp',
      packageNo: '',
      uom: 'PC',
      qtyReq: 8,
      qtyIssued: 'PC',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Patch Cord',
    },
    {
      id: 'mi_bench_7',
      partNumber: '3FE76476AA',
      description: 'LightspanMF-2 240Gbps NT with clock sync(brand: Nokia) (LMNT-A)',
      packageNo: '',
      uom: 'PC',
      qtyReq: 2,
      qtyIssued: 'PC',
      qtyReceived: '',
      qtyBalance: '',
      category: 'MF2',
    },
    {
      id: 'mi_bench_8',
      partNumber: '3FE76353AA',
      description: 'Lightspan MF 16port Multi-PON Line board (LWLT-C)',
      packageNo: '',
      uom: 'PC',
      qtyReq: 1,
      qtyIssued: 'PC',
      qtyReceived: '',
      qtyBalance: '',
      category: 'MF2',
    },
  ],
  localMaterials: [
    {
      id: 'lm_bench_1',
      partNumber: '3FE52344FLAA',
      description: 'Simplex patch cord, LC/UPC - LC/UPC 8m(brand: Nokia)',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 2,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Patch Cord',
    },
    {
      id: 'lm_bench_2',
      partNumber: 'Blaine-Spiral-1/2mmx10ft',
      description: 'Spiral Wrap 10mmx10ft',
      packageNo: '',
      uom: 'pc',
      qtyReq: 1,
      qtyIssued: 'pc',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Consumables',
    },
    {
      id: 'lm_bench_3',
      partNumber: 'L00HLT_VELCRO_10M',
      description: 'VELCRO (HOOK & LOOP TIE) BLACK 10m/roll',
      packageNo: '',
      uom: 'pc',
      qtyReq: 1,
      qtyIssued: 'pc',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Consumables',
    },
    {
      id: 'lm_bench_4',
      partNumber: 'Blaine-16mm-Shrinkable',
      description: 'Shrinkable tube 16mm x 200mm',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 2,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Consumables',
    },
    {
      id: 'lm_bench_5',
      partNumber: 'Blaine-8mmShrinkable',
      description: 'Shrinkable tube 8mm x 200mm',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 2,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Consumables',
    },
    {
      id: 'lm_bench_6',
      partNumber: 'Blaine-12mmShrinkable',
      description: 'Shrinkable tube 12mm x 200mm',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 2,
      qtyIssued: 'pcs',
      qtyBalance: '',
      qtyReceived: '',
      category: 'Consumables',
    },
    {
      id: 'lm_bench_7',
      partNumber: 'Blaine-Cartridge9mm',
      description: 'Labeller tape',
      packageNo: '',
      uom: 'pc',
      qtyReq: 1,
      qtyIssued: 'pc',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Consumables',
    },
    {
      id: 'lm_bench_8',
      partNumber: 'L00TL14AWG',
      description: 'cable shoe (#14 AWG)',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 4,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Hardware',
    },
    {
      id: 'lm_bench_9',
      partNumber: 'L00Lugs10mm2',
      description: '10mm2 Terminal Lugs',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 6,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Hardware',
    },
    {
      id: 'lm_bench_10',
      partNumber: 'L00Lugs16mm2',
      description: '16-10mm2 Terminal Lugs',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 2,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Hardware',
    },
    {
      id: 'lm_bench_11',
      partNumber: 'L00Lugs8mm2',
      description: 'terminal lugs 8mm',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 6,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Hardware',
    },
    {
      id: 'lm_bench_12',
      partNumber: '3FE77365BAAA',
      description: 'POSITIVE POWER CABLE BLACK/10M',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 2,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Power Cable',
    },
    {
      id: 'lm_bench_13',
      partNumber: '3FE60713CAAA',
      description: 'Simplex Patch Cord, SC/UPC - SC/APC 2m(brand: Nokia)',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 16,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Patch Cord',
    },
    {
      id: 'lm_bench_14',
      partNumber: 'L00YG16MM2',
      description: 'WIRE GROUNDING CABLE YELLOW/GREEN 16MM N/A',
      packageNo: '',
      uom: 'm',
      qtyReq: 10,
      qtyIssued: 'm',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Power Cable',
    },
    {
      id: 'lm_bench_15',
      partNumber: '3FE77035BA',
      description: 'Lightspan MF LT dmmy plte (388x204x25)mm',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 1,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'MF2',
    },
    {
      id: 'lm_bench_16',
      partNumber: 'Blaine-8"Tie',
      description: 'Plastic Cable Tie white',
      packageNo: '',
      uom: 'pcs',
      qtyReq: 1,
      qtyIssued: 'pcs',
      qtyReceived: '',
      qtyBalance: '',
      category: 'Consumables',
    },
  ],
  signatures: {
    requestedBy: {
      name: 'JOHN CARLO RABANES',
      title: 'Nokia Inhouse Engineer',
      date: '2026-06-30',
    },
    contactNokiaInhouse: 'NOKIA INHOUSE - JOHN CARLO RABANES/09669343065',
    contactSubcon: 'DNA SUBCON - EASTMOND MIRANDA/09543991868',
    preparedBy: {
      name: '',
      title: '',
      date: '',
    },
    receivedBy: {
      name: '',
      title: '',
      date: '',
    },
    status: 'Accepted',
    remarks: 'Verified complete and matching official sample NOKIA-FN_06302026-004_MIN1371-GNG-701_MF2_JOHN_CARLO_RABANES',
  },
};

export const ADDITIONAL_FILLED_SAMPLES: MRFDocument[] = [];
